apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-microservice
spec:
  selector:
    matchLabels:
      app: api-gateway-microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway-microservice
    spec:
      containers:
        - name: api-gateway-microservice
          image: api-gateway-microservice:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
