apiVersion: v1
kind: Service
metadata:
  name: api-gateway-microservice-svc
spec:
  selector:
    app: api-gateway-microservice
  ports:
    - protocol: "TCP"
      port: 9090 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.