apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-microservice
spec:
  selector:
    matchLabels:
      app: second-microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: second-microservice
    spec:
      containers:
        - name: second-microservice
          image: second-microservice:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
