apiVersion: v1
kind: Service
metadata:
  name: second-microservice-svc
spec:
  selector:
    app: second-microservice
  ports:
    - protocol: "TCP"
      port: 9091
      targetPort: 8082
  type: NodePort # type of the service.