server:
  ssl:
    key-store: classpath:apigatewayhttps.jks
    key-store-password: password
    key-store-type: pkcs12
    key-alias: apigatewayhttps
    key-password: password
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  application:
    name: api-gw
  cloud:
    gateway:
      routes:
        - id: first-microservice
          uri: http://localhost:8081/
          predicates:
            - Path=/first/**
        - id: second-microservice
          uri: http://localhost:8082/
          predicates:
            - Path=/second/**