apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-microservice
spec:
  selector:
    matchLabels:
      app: first-microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: first-microservice
    spec:
      containers:
        - name: first-microservice
          image: first-microservice:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
